name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  update-readme:
    name: Waka readme dev metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          IGNORED_LANGUAGES: CSS HTML Less JSON Markdown SCSS TeX TOML YAML
